"""add_email_to_user

Revision ID: 205bf903beab
Revises: c175985f812d
Create Date: 2026-05-23 12:56:48.077417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205bf903beab'
down_revision = 'c175985f812d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
