"""init_foodtime_tables

Revision ID: c175985f812d
Revises: 
Create Date: 2026-05-19 20:09:20.836153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c175985f812d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canteens',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('open_hours', sa.String(length=100), nullable=True),
    sa.Column('avg_price', sa.String(length=50), nullable=True),
    sa.Column('peak_queue', sa.String(length=50), nullable=True),
    sa.Column('best_time', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('rant', sa.Text(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('signature_dishes', sa.JSON(), nullable=True),
    sa.Column('student_notes', sa.JSON(), nullable=True),
    sa.Column('intro_blocks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canteens'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('account_status', sa.String(length=20), nullable=False),
    sa.Column('current_points', sa.Integer(), nullable=False),
    sa.Column('total_earned_points', sa.Integer(), nullable=False),
    sa.Column('total_used_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_account'), ['account'], unique=True)

    op.create_table('dish_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('canteen_name', sa.String(length=100), nullable=False),
    sa.Column('stall_name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('submitter_account', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('audit_reason', sa.Text(), nullable=True),
    sa.Column('auditor_account', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_account'], ['users.account'], name=op.f('fk_dish_submissions_auditor_account_users')),
    sa.ForeignKeyConstraint(['submitter_account'], ['users.account'], name=op.f('fk_dish_submissions_submitter_account_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dish_submissions'))
    )
    op.create_table('point_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=False),
    sa.Column('source_or_dest', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_point_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_point_records'))
    )
    with op.batch_alter_table('point_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_records_user_id'), ['user_id'], unique=False)

    op.create_table('rants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canteen_name', sa.String(length=100), nullable=True),
    sa.Column('author_account', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('audit_reason', sa.Text(), nullable=True),
    sa.Column('auditor_account', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_account'], ['users.account'], name=op.f('fk_rants_auditor_account_users')),
    sa.ForeignKeyConstraint(['author_account'], ['users.account'], name=op.f('fk_rants_author_account_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rants'))
    )
    op.create_table('stalls',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('canteen_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('avg_price', sa.String(length=50), nullable=True),
    sa.Column('best_time', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canteen_id'], ['canteens.id'], name=op.f('fk_stalls_canteen_id_canteens')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stalls'))
    )
    op.create_table('dishes',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('stall_id', sa.String(length=100), nullable=False),
    sa.Column('canteen_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_note', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('recommend_votes', sa.Integer(), nullable=False),
    sa.Column('avoid_votes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canteen_id'], ['canteens.id'], name=op.f('fk_dishes_canteen_id_canteens')),
    sa.ForeignKeyConstraint(['stall_id'], ['stalls.id'], name=op.f('fk_dishes_stall_id_stalls')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dishes'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dish_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name=op.f('fk_reviews_dish_id_dishes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('dishes')
    op.drop_table('stalls')
    op.drop_table('rants')
    with op.batch_alter_table('point_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_records_user_id'))

    op.drop_table('point_records')
    op.drop_table('dish_submissions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_account'))

    op.drop_table('users')
    op.drop_table('canteens')
    # ### end Alembic commands ###
